### ISSUE TITLE
Failed to place piston 1.19.2

### ISSUE THREAD

**Issue by b3rgg** [Bunnui/Fabric-Bedrock-Miner#9]
Mod "Bedrock Miner 1.19.2 " does not work on the server, it gives the error "Failed to place piston!". Server core "Pufferfish".

On "Vanilla" the mod works fine.

Thanks, I hope you can help.

**Comment by Bunnui** [comment]
https://github.com/Bunnui/Fabric-Bedrock-Miner/blob/dc22246ebc50a03f435132487b3a27c670dd841f/src/main/java/yan/lx/bedrockminer/utils/TargetBlock.java#L143-L162


This code blockPos may be incorrectly filled in during the development process. PistonBlockPos should be used

```c#
CheckingEnvironment.has2BlocksOfPlaceToPlacePiston(world, this.blockPos)
```

**Comment by b3rgg** [comment]
Weird.
It didn't help. Bedrock still does not break. Maybe the problem is in the server core?

Thanks

**Comment by b3rgg** [comment]
All blocks are placed, but the bedrock does not break. I also tried to break the obsidian - it also does not break.

**Comment by Bunnui** [comment]
I can't find the "Pufferfish" download address
If you are using a Paper-based server, you may need to modify the configuration in paper to allow it to operate
```
path: paper\config\paper-global.yml

unsupported-settings:
  allow-headless-pistons: false
  allow-permanent-block-break-exploits: false ——> true
  allow-piston-duplication: false
  perform-username-validation: true
```

set " allow-permanent-block-break-exploits" value  "false" --> "true " setting


you try this version, download address : https://github.com/Bunnui/Fabric-Bedrock-Miner/suites/10169789417/artifacts/497272834
